exclude: "templates"

default_language_version:
  python: python3.12

repos:
  # general checks (see here: https://pre-commit.com/hooks.html)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # black - formatting
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        name: black
        args:
          - "--config"
          - "./pyproject.toml"

  # ruff - linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.2.2"
    hooks:
      - id: ruff
        name: ruff

  # mypy - lint-like type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies: [types-requests==2.31.0.20240218]
        args: [--config-file=pyproject.toml, --ignore-missing-imports]

  # bandit - find common security issues
  # - repo: https://github.com/pycqa/bandit
  #   rev: 1.7.7
  #   hooks:
  #     - id: bandit
  #       name: bandit
  #       exclude: ^tests/,^cprex/commands.py
  #       args:
  #         - -r
  #         - cprex
