name: Publish to Test PyPI

on:
  push:
    tags:
      - "v*.*.*"

env: # environment variables (available in any part of the action)
  PYTHON_VERSION: 3.11

jobs:
  pre-publish:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Config Repository
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/

      - name: Login to PyPI Test
        run: poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}

      - name: Publish package
        run: poetry publish --build -r testpypi
