[server]
# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 10

[theme]
# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#f0f2f699"
